### 0. 대표적인 데이터 분석용 라이브러리
- 넘파이(Numpy) : 넘파이 배열, 리스트의 확장판
- 판다스(Pandas) : 테이블 형태의 데이터 처리, 딕셔너리의 확장판
- 맷플롯립(Matplotlib) : 파이썬의 시각화를 담당하는 라이브러리
- 외부모듈을 설치할 경우는 파이썬 파이프연산을 통해서 패키지 설치
- pip install numpy pandas matplotlib  -(아나콘다 프롬프트에서 실행)

In [1]:
# list
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 0]
a+b  # append

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [3]:
# 라이브러리 로딩
import numpy as np
arr1 = np.array(a)  # 넘파이 배열 만들기 np.array
arr2 = np.array(b)
arr1 + arr2

array([ 7,  9, 11, 13,  5])

In [4]:
print(type(arr1))
print(type(a))

<class 'numpy.ndarray'>
<class 'list'>


In [5]:
len(a)

5

In [7]:
# 넘파이 배열의 크기(size), shape
arr1.shape  # (행, 열)로 표현, 행만 표시되면 1차원배열

(5,)

In [9]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [11]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = []
for i in data:
    answer.append(i*2)
print(answer)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [13]:
answer=[i*2 for i in data]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [14]:
x = np.array(data)
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# 벡터화(수치화, 정량화) 연산
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [16]:
a+b

array([11, 22, 33])

In [17]:
a-b

array([ -9, -18, -27])

In [18]:
# 비교연산
a == 2 # 비교연산자와 관계연산자의 결과 True or False

array([False,  True, False])

In [19]:
b > 10

array([False,  True,  True])

In [20]:
(a == 2) & (b > 10)  # & : and

array([False,  True, False])

In [21]:
# 2차원 배열 : 행(가로, row)과 열(세로, column)
a = [[0, 1, 2], [3, 4, 5]]
a

[[0, 1, 2], [3, 4, 5]]

In [24]:
c = np.array([[0, 1, 2], [3, 4, 5]])   # 2x3  - 2행3열
c

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
# 행의 개수
len(a)  

2

In [26]:
len(c)

2

In [28]:
# 열의 개수
len(c[0])

3

In [29]:
c.shape  # (행,열)

(2, 3)

In [33]:
# 3차원 배열 생성  2 x 3 x 4(면,행,렬)
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [34]:
# 면, 행, 열
print(len(d), len(d[0]), len(d[0][0]))

2 3 4


In [35]:
# 배열의 차원-ndim과 크기(속성)-shape   # ndim = len + dimension
d.shape

(2, 3, 4)

In [36]:
d.ndim  # 차원

3

In [37]:
# 배열의 인덱싱
import numpy as np
a = np.array([0, 1, 2, 3, 4])
a[2]

2

In [38]:
a[-1]

4

In [40]:
b = np.array([[0, 1, 2], [3, 4, 5]])  # 2x3
b

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
# [조건식], [행, 열]
b[0, 0]  # b[0][0]

0

In [43]:
b[1, 1]  # b[1][1]

4

In [45]:
# 마지막행 마지막열
b[-1, -1]

5

In [46]:
# 슬라이싱(slicing)
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  # 2x4
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
# 첫번째 행 [행, 열], [시작값:마지막값]
# c[행, 열]  => c[행, :]  열은 모두 가져옴
c[0, :]

array([1, 2, 3, 4])

In [48]:
# 두번째 열 전체
c[:,1]

array([2, 6])

In [49]:
# 두번째 행의 두번째 열부터 끝 열까지
c[1,1:]

array([6, 7, 8])

In [61]:
c[:,:2]

array([[1, 2],
       [5, 6]])

In [68]:
# 펜시 인덱싱 - Boolean Indexing
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, 
                False, True, False, True, False])

a[idx]   # 요소의 개수는 같아야한다 # True만 출력

array([0, 2, 4, 6, 8])

In [70]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [73]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [74]:
a[a%2 == 0]

array([0, 2, 4, 6, 8])

In [75]:
# 넘파이 자료형, type => dtype, 배열의 자료형을 읽어오는 속성
x = np.array([1, 2, 3])
print(x.dtype)  # 32비트 정수, 64비트 정수
# print(type(x))

int32
<class 'numpy.ndarray'>


In [76]:
x = np.array([1.0, 2.0, 3.0])  # float은 32비트가 없음
x.dtype

dtype('float64')

In [77]:
x = np.array([1, 2, 3.0])  # 큰 자료형으로 캐스팅됨 - promotion
x.dtype

dtype('float64')

In [79]:
x  # 정수(int)도 실수(float)로 저장이 됨

array([1., 2., 3.])

In [81]:
x = np.array([1, 2, 3])
print(x.dtype)
x = np.array([1, 2, 3], dtype = 'f')  # f (float)
print(x.dtype)

int32
float32


In [115]:
x = np.array([1, 2, 3], dtype = 'U')  # u (unsign int), 부호없는 정수
print(x.dtype)  # B

<U1


In [105]:
x  # 문자열 - 유니코드 dtype='U'

array(['1', '2', '3'], dtype='<U1')

In [116]:
# inf( infinite ; 무한대)와 NaN(정의할 수 없는 숫자)
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([  0.,  inf, -inf,  nan])

In [117]:
np.log(0)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [122]:
# 배열 생성 명령 : 단순한 배열을 생성하는 명령어
# zeros, ones  - 배열의 모든 요소를 0으로 만들어라, 1로 만들어라
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [124]:
# 배열의 크기 : (행, 열)
b = np.zeros((2, 3))  # 2행3열 배열에 0을 채움
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [126]:
c = np.zeros((2, 3), dtype='i')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [133]:
# 문자열 배열도 가능, 단 모든 원소의 문자열 크기가 같아야 한다.
d = np.zeros(5, dtype='U')  # U-4비트 문자열, U4-16비트 문자열
d  # 문자열의 크기가 같아야함, 비어있는 공간 만들때 사용

array(['', '', '', '', ''], dtype='<U1')

In [135]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d[3] = "ABCDEFGH"
d                 # U - 1글자 이하

array(['a', 'a', 'A', 'A', ''], dtype='<U1')

In [136]:
d = np.zeros(5, dtype='U4')
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d[3] = "ABCDEFGH"
d                 # U4 - 4글자 이하

array(['abc', 'abcd', 'ABCD', 'ABCD', ''], dtype='<U4')

In [137]:
e = np.ones((2, 3, 4), dtype='i') # 2면3행4열
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [142]:
# ones_like, zeros_like : 배열의 크기를 명시하지 않고
# 다른 배열의 크기를 가져다 쓰고싶을 때 사용 # 1과같은, 0과같은

f = np.ones_like(b)
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [143]:
# empty 
g = np.empty((4, 3))  # 4행 3열 행렬,, 초기화 - 니가 알아서 값 넣어줘
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [144]:
import numpy as np
# arange : range의 Numpy 버전
np.arange(10)    # 0 ~ n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
np.arange(3, 21, 2)  # 시작, 끝(포함x), 증감

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [146]:
# linspace-선형구간 와 logspace-로그구간 명령
# 분할해서 만들어라? linear space
np.linspace(0, 100, 5)  # 시작, 끝(포함), 개수

array([  0.,  25.,  50.,  75., 100.])

In [152]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [154]:
# 전치연산 : 행과 열을 바꾸는 기능, T
A = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3
A

array([[1, 2, 3],
       [4, 5, 6]])

In [156]:
A.T # 3x2  A를 전치함  transposed matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [157]:
# 배열의 크기 변형
# shape : 배열의 속성 확인
# reshape(행, 열)
a = np.arange(12)  # 0 ~ 11
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [158]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 열의 값이 정해져있으면 행의 값이 생략될 수 있다

In [163]:
a.reshape(3, -1)  # 3행x열, 3등분해라

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
a.reshape(2, 2, -1)  # 2면2행, 열의 값은 자동처리

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [167]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [168]:
x = np.arange(5)
x          

array([0, 1, 2, 3, 4])

In [169]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [173]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [174]:
# 벡터(Vector)화 연산
a = np.array([1, 2, 3, 4]) # 정량화, 연산 가능, 인수로 계산
b = np.array([4, 2, 2, 4]) # 리스트에선 + 연결, * 반복

In [175]:
a+b   # 요소별로 +,-,*,/

array([5, 4, 5, 8])

In [176]:
a-b

array([-3,  0,  1,  0])

In [177]:
a*b

array([ 4,  4,  6, 16])

In [178]:
a/b

array([0.25, 1.  , 1.5 , 1.  ])

In [179]:
a == b

array([False,  True, False,  True])

In [180]:
a >= b

array([False,  True,  True,  True])

In [181]:
# all() : 모든 요소를 대상으로 비교하는 작업
np.all(a == b)

False

In [182]:
c = np.array([1, 2, 3, 4]) # a=np.array([1, 2, 3, 4]) 
np.all(a==c)  # 모든 요소 -위치와 값이 같은지 확인

True

In [12]:
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [3]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [ ]:
# 내장함수
# min, max, sum, mean(평균), median,
# std(표준편차), var(분산), all, any

In [18]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [19]:
np.sum(x)

10

In [20]:
# argmin - 최솟값의 위치, argmax - 최댓값의 위치
# argmin, argmax
np.min(x)

1

In [21]:
np.argmin(x)

0

In [22]:
np.max(x)

4

In [23]:
np.argmax(x)

3

In [24]:
x.mean()  # 평균

2.5

In [27]:
np.mean(x)

2.5

In [30]:
np.median(x) # 중앙값

2.5

In [31]:
np.all([True, True, False])  # 모든 요소가 참입니까?

False

In [32]:
np.any([True, True, False]) #어느거 하나라도 참입니까?

True

In [33]:
np.any([1, 1, 0])

True

In [35]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [36]:
np.sum(x)

10

In [37]:
x.sum()

10

In [40]:
# 열의 합계 or 행의 합계만 구하기
x.sum(axis=0)  # axis=0 -> 열

array([4, 6])

In [41]:
x.sum(axis=1)  # 행 단위 합계 axis=1  /판다스는 반대

array([3, 7])

In [45]:
a = np.array([[1, 2], [3, 4]], dtype='i')
b = np.array([[1, 2], [3, 4]], dtype='i')
print(a)
print(b)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [48]:
print(a+b)
print(a-b)
print(a*b)   # 행렬곱 아님,,,, 요소 간의 곱
print(a/b)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[1. 1.]
 [1. 1.]]
