In [ ]:
# count : 데이터 개수
# 평균 : mean, average
# 분산 : var, variance
# 표준편차 : std, standard deviation
# 최댓값 : maximum
# 최솟값 : minimum
# 중앙값 : median
# 사분위수 : quartile

In [3]:
import numpy as np
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 5, 2,
              15, 8, 2, 5, 4, 15, -1, 4, -7, -24,
              7, 9, -6, 23, -13])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   5,   2,  15,   8,   2,
         5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [4]:
len(x)

25

In [5]:
np.mean(x)

5.0

In [6]:
np.var(x)  # 분산

118.88

In [7]:
np.std(x)  # 표준편차

10.903210536351208

In [8]:
np.max(x)

23

In [9]:
np.min(x)

-24

In [10]:
np.median(x)

5.0

In [13]:
# 백분위수(percentile)
np.percentile(x, 0)  
# 0-> 0위치에 있는거,, 최솟값
# 100-> 100위치에 있는거,, 최댓값
#사분위수 - 0~100 중 4등분

-24.0

In [14]:
np.percentile(x, 100)  # 최댓값

23.0

In [15]:
np.percentile(x, 25)  # 1사분위수 = 100분위수25

0.0

In [16]:
np.percentile(x, 50)  # 2사분위수 = 중앙값

5.0

In [17]:
np.percentile(x, 75)  # 3사분위수

10.0

In [19]:
# 난수 발생
# rand() : 0과 1 사이의 난수를 발생시키는 함수 #()개수
np.random.rand(5)  # rand - 정규분포

array([0.10691842, 0.17960828, 0.94103586, 0.08654805, 0.91144392])

In [20]:
np.random.rand(10)

array([0.38519099, 0.97646625, 0.9805056 , 0.62878432, 0.4166104 ,
       0.39741788, 0.80565152, 0.32473066, 0.86430079, 0.13908988])

In [21]:
np.random.rand(10)

array([0.33434611, 0.17008643, 0.36995693, 0.34750005, 0.35673193,
       0.11451605, 0.4826998 , 0.1101034 , 0.8279105 , 0.29540307])

In [22]:
# shuffle() : 데이터를 섞는다.
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.random.shuffle(x)  # x값을 무작위로 섞어라
x

array([5, 6, 4, 2, 9, 8, 3, 7, 0, 1])

In [45]:
np.random.choice(5, 5)     # sampling (개수,range(5))

array([0, 2, 3, 3, 2])

In [67]:
np.random.choice(5, 5, replace=False) # 중복 허용x

array([1, 4, 3, 0, 2])

In [71]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 확률값
# 0~4 숫자를 10개 만든 후, 확률에 따라 선택

array([0, 3, 3, 3, 3, 3, 2, 3, 2, 3], dtype=int64)

In [ ]:
# rand : 0에서 1 사이의 균일 분포
# randn : 표준정규분포를 이용한 난수 발생
# randint : 균일분포의 정수 난수 

# 분산- 편차²의 평균, 표준편차- sqrt(분산)

In [91]:
np.random.rand(10)  # 균일한 확률로 난수발생(실수값)

array([0.19326463, 0.04987393, 0.85089977, 0.05503595, 0.20871284,
       0.35573335, 0.33936463, 0.79935952, 0.33776828, 0.12286536])

In [92]:
np.random.rand(3, 5)  # 3행 5열의 크기로 난수발생
                      # 차원 - (행, 열)

array([[0.91554978, 0.34854065, 0.64686118, 0.42847921, 0.43096848],
       [0.84830573, 0.26509192, 0.92322527, 0.00611254, 0.68337124],
       [0.56998347, 0.98304881, 0.36744354, 0.85803786, 0.66713596]])

In [94]:
np.random.randn(10)  # 표준정규분포 (평균0, 표준편차1)

array([-0.4363983 ,  0.19516901,  0.84145997, -0.24160112,  0.85303645,
        0.74538604,  1.6386046 ,  1.06806366,  0.75214083, -0.26754669])

In [ ]:
np.random.randn(3, 5)

In [84]:
# randint(low, high, size)
# randint 균일분포 -> 정수값/ 옵션3개(최소,하이,개수)
np.random.randint(10, size=10) # 0~10미만, 10개

array([3, 4, 5, 3, 6, 2, 6, 5, 4, 9])

In [85]:
np.random.randint(10, 20, size=10) # 10~20

array([10, 15, 12, 13, 19, 16, 15, 12, 10, 14])

In [86]:
np.random.randint(10, 20, size=(3, 5))

array([[18, 17, 19, 11, 13],
       [19, 13, 18, 10, 13],
       [11, 10, 13, 19, 16]])

In [ ]:
# 소주뚜껑 숫자맞추기 게임