In [2]:
# 표준 라이브러리 로딩
import numpy as np
import pandas as pd
# from pandas import Series, DataFrame

In [ ]:
# Series : 1차원 배열, index + values
obj = pd.Series([4, 7, -5, 3])
obj

In [ ]:
obj.index

In [ ]:
obj.values

In [ ]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

In [ ]:
obj2['a']

In [ ]:
obj2['d'] = 6
obj2

In [ ]:
obj2[['c', 'a', 'd']]

In [ ]:
obj2[obj2 > 0]

In [ ]:
obj2 *2

In [ ]:
'b' in obj2

In [ ]:
'e' in obj2

In [ ]:
# 파이썬의 사전을 이용해서 Series를 생성
# 사전에서 key가 Series의 index가 된다.
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
obj3 = pd.Series(sdata)
obj3

In [ ]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)  # 캘리포니아 존재x -> 결측처리NaN
obj4

In [ ]:
# 결측값을 찾는 함수 : isnull(), notnull()
pd.isnull(obj4)

In [ ]:
pd.notnull(obj4)

In [ ]:
obj4

In [ ]:
# name 속성
obj4.name = 'population'
obj4.index.name = 'state'
obj4

In [ ]:
obj

In [ ]:
# index 변경
obj.index

In [ ]:
obj.index = {'Bob', 'Steve', 'Jeff', 'Ryan'}
obj

### DataFrame
- 표 형태의 자료구조
- 여러 개의 컬럼이 존재하고, 각 컬럼은 서로 다른 값을 담을 수 있다.
- 2차원 배열

In [ ]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year':[2000, 2001, 2002, 2001, 2002, 2003],
       'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.7]}
frame = pd.DataFrame(data)
frame

In [ ]:
# head(), tail() : 데이터프레임 내용의 앞, 뒷단 5개 row를 표시
frame.head()

In [ ]:
frame.head(3)

In [ ]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

In [ ]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one','two','three','four','five','six'])
frame2

In [ ]:
frame2.columns  # object타입- 문자열.. (문자+숫자 일때 오브젝트라고 나타남)

In [ ]:
frame2.index

In [ ]:
frame2['state']

In [ ]:
frame2.year

In [ ]:
# 특정 행은 위치나 loc속성
frame2.loc['three']

In [ ]:
frame2['debt'] = 16.5
frame2

In [ ]:
frame2['debt'] = np.arange(6.) # float타입으로 0.0~5.0까지 debt에 넣음
frame2

In [ ]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

In [ ]:
# del 예약어를 통해 컬럼을 삭제
frame2['eastern'] = frame2.state == 'Ohio'
frame2

In [ ]:
del frame2['eastern']
frame2

In [ ]:
# 중첩된 사전을 이용한 데이터프레임 생성
pop = {'Nevada':{2001:2.4, 2002:2.9},
      'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

In [ ]:
frame3.T

In [ ]:
pd.DataFrame(pop, index = [2001, 2002, 2003])

In [ ]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

In [ ]:
frame3

In [ ]:
# name 속성
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

In [ ]:
frame3.values

In [ ]:
frame2.values

### DataFrame의 인덱스

In [ ]:
obj = pd.Series(range(3), index=['a','b','c'])
obj

In [ ]:
obj.index

In [ ]:
index = obj.index
index

In [ ]:
index[1:]

In [ ]:
# 색인 객체는 변경이 불가능하다.
index[1] = 'd' # array가 아니라 index 객체,,

In [ ]:
# 재색인 : reindex
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d','b','a','c'])
obj

In [ ]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

In [ ]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])
obj3

In [ ]:
obj3.reindex(range(6))

In [ ]:
# 누락된 값을 직전의 값으로 채워주는 역할
obj3.reindex(range(6), method='ffill')  # 결측값이, 이전값으로 채워짐

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                   index=['a','c','d'],
                   columns=['Ohio','Texas','Callifornia'])
frame

In [ ]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

In [ ]:
states = ['Texas','Utah', 'Callifornia']
frame.reindex(columns=states)

In [ ]:
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])
obj

In [ ]:
new_obj = obj.drop('c')  # 특정 index 의 행을 삭제 # 원본은 그대로
new_obj

In [ ]:
obj.drop(['d','c'])

In [ ]:
obj

In [ ]:
obj.drop(['d','c'], inplace=True)  # 삭제한 것이 원본에 반영
obj

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio','Colorado','Utah','NewYork'],
                    columns=['one','two','three','four'])
data

In [ ]:
data.drop(['Colorado', 'Ohio']) # axis=0 생략된 것

In [ ]:
# 컬럼을 삭제할 경우 반드시 축(axis)를 넘겨줘야 한다.
data.drop('two', axis=1)  # axis='columns'

In [ ]:
data.drop('three', axis='columns')

In [ ]:
data.drop(['two', 'four'], axis='columns')

In [ ]:
data

In [ ]:
obj = pd.Series(np.arange(4.), index=['a','b','c','d'])
obj

In [ ]:
obj[1]

In [ ]:
obj['b']

In [ ]:
obj[2:4]

In [ ]:
obj[['b','a','d']]

In [ ]:
obj[[1, 3]]

In [ ]:
obj[obj < 2]

In [ ]:
obj['b':'c']  # 문자로 슬라이싱하면, 라벨(마지막)까지 다 나옴

In [ ]:
obj[1:3]  # 숫자로 슬라이싱하면 마지막-1 까지 나옴

In [ ]:
obj['b':'c'] = 5
obj

In [ ]:
data

In [ ]:
data['two']

In [ ]:
data[['three', 'one']]  # 추출 순서대로 정렬되어 나옴

In [ ]:
data[:2]  # row  0,1

In [ ]:
data[data['three'] > 5]

In [ ]:
data < 5  # 각 값을 5와 비교하여 boolean으로 나타남

In [ ]:
data[data<5] = 0
data

In [ ]:
# loc, iloc 속성
# loc : 축 이름을 선택할 때
# iloc : 정수 인덱스를 선택할 때

In [ ]:
# [행, 열]
data.loc['Colorado', ['two','three']]

In [ ]:
data.iloc[1, [1,2]]

In [ ]:
data.iloc[2]

In [ ]:
data.iloc[[1,2], [3,0,1]]

In [ ]:
data.loc[:'Utah', 'two']

In [ ]:
data.iloc[:, :3][data.three > 5]  # 대괄호 안에선 따옴표 붙이지만, 다이렉트(.)에선 따옴표를 붙이지않음

In [ ]:
ser = pd.Series(np.arange(3.))
ser

In [ ]:
ser[-1]

In [ ]:
ser[-1:]

In [ ]:
ser2 = pd.Series(np.arange(3.), index=['a','b','c'])
ser2[-1]

In [ ]:
ser[1]

In [ ]:
ser[:1]

In [ ]:
# 라벨
ser.loc[:1]

In [ ]:
# 정수색인
ser.iloc[:1]  # 일관성이 떨어지니,, iloc를 쓰는게 좋다

### 산술 연산

In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a','c','d','e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a','c','e','f','g'])

In [ ]:
s1

In [ ]:
s2

In [ ]:
s1+s2  # 값이 존재하지 않으면 결측값이 나옴. NaN, 누락값

In [16]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),
                  columns=list('bcd'), index=['Ohio','Texas','Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),
                   columns=list('bde'), index=['Utah','Ohio','Texas','Oregon'])

In [17]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [18]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [20]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [7]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[3,4]})

In [4]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [8]:
df1.add(df2, fill_value=0)

A    B
0  1.0  3.0
1  2.0  4.0

In [13]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [14]:
arr[0]

array([0., 1., 2., 3.])

In [15]:
arr-arr[0]  # 각각 대입을 한다... broadcasting...

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [21]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                   columns=list('bde'), index=['Utah','Ohio','Texas','Oregon'])
series = frame.iloc[0]

In [22]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [23]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [24]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [25]:
series2 = pd.Series(range(3), index=['b','e','f'])
series2  # 값이 존재하지 않으면 reindex 처리가 됨

b    0
e    1
f    2
dtype: int64

In [26]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [27]:
frame = pd.DataFrame(np.random.randn(4,3),
                   columns=list('bde'), index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    1.689136  0.979349  0.915259
Ohio   -0.454015  0.207257  1.669941
Texas  -1.710221  0.432241 -1.711775
Oregon -1.377579  1.147272  1.625349

In [28]:
np.abs(frame)  # abs 절댓값

b         d         e
Utah    1.689136  0.979349  0.915259
Ohio    0.454015  0.207257  1.669941
Texas   1.710221  0.432241  1.711775
Oregon  1.377579  1.147272  1.625349

In [29]:
# frame 데이터에서 각 로우마다 최댓값에서 최솟값을 뺀 결과값을 추출하려면
# apply() : 특정 함수를 이용하여 반복적인 계산을 수행할 때 사용한다.   cf> map
# lambda 입력 : 출력
f = lambda x : x.max() - x.min()
frame.apply(f)

b    3.399357
d    0.940015
e    3.381715
dtype: float64

In [30]:
frame.apply(f, axis='columns')

Utah      0.773877
Ohio      2.123955
Texas     2.144016
Oregon    3.002928
dtype: float64

In [31]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])

frame.apply(f)

b         d         e
min -1.710221  0.207257 -1.711775
max  1.689136  1.147272  1.669941

In [32]:
frame

b         d         e
Utah    1.689136  0.979349  0.915259
Ohio   -0.454015  0.207257  1.669941
Texas  -1.710221  0.432241 -1.711775
Oregon -1.377579  1.147272  1.625349

In [38]:
fmt = lambda x : '%.2f' % x
frame.applymap(fmt)  # 문자열('%.2f') 서식에선 applymap을 씀

b     d      e
Utah     1.69  0.98   0.92
Ohio    -0.45  0.21   1.67
Texas   -1.71  0.43  -1.71
Oregon  -1.38  1.15   1.63

In [39]:
frame['e'].map(fmt)  # dtype이 float이 아니라 object로 나옴,,

Utah       0.92
Ohio       1.67
Texas     -1.71
Oregon     1.63
Name: e, dtype: object