In [1]:
import numpy as np
w = np.array([2, 1, 5, 3])
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])

In [2]:
w_r = np.flip(w)
w_r

array([3, 5, 1, 2])

In [3]:
w_r = w[::-1]
w_r

array([3, 5, 1, 2])

합성곱 연산은 두 함수 f, g 가운데 하나의 함수를 반전(reverse), 전이(shift)시킨 다음,  
다른 하나의 함수와 곱한 결과를 적분하는 것을 의미

In [6]:
# 한 칸씩 이동하면서 합성곱을 수행하는 함수 : 점곱(dot)
for i in range(6):
    print(np.dot(x[i:i+4], w_r))

63
48
49
28
21
20


In [8]:
from scipy.signal import convolve  # convolution function 합성곱
convolve(x, w, mode='valid')

array([63, 48, 49, 28, 21, 20])

가중치=커널(Kernel)=필터(Filter) ...=뉴런

![image](https://user-images.githubusercontent.com/58851945/119423385-20bfe100-bd3e-11eb-921f-9ffbc107d333.png)

padding='same'  : 입력층과 동일한 크기의 출력층을 만들어냄
'valid'를 쓰면 크기가 줄어들음 (일반적인 합성곱)

커널이 합성곱을 할 때
한칸씩 말고 여러칸씩 이동 가능 -> 스트라이드(Stride)

합성곱으로 특성맵이 만들어짐
특성맵(2,2,3) = 특성맵 크기(가로,세로), 필터의 개수(=차원,채널)

풀링 -> 크기를 줄임
4개의 픽셀을 하나로 압축
필터의 개수는 그대로 유지

최대풀링(MaxPooling) : 가장 큰값을 담음. 일반적으로 많이 쓰임
평균풀링 : 평균을 구해서 담음

풀링은 가중치가 없음

풀링은 겹치지 않게 이동함
ex. (2,2)풀링 => 2칸씩 이동
(3,3)풀링 => 3칸씩 이동

(stride는 생략해도됨(풀링 크기 = 이동크기).
padding='valid'-> 생략가능(크기가 줄어들기 때문에))


MaxPooling2D(2)  <- 2x2풀링

마지막엔 꼭 한개 이상의 밀집층이 있어야함
밀집층 -> 전체를 연결시켜줌
1차원으로 펼치고, 소프트맥스라는 활성화함수 사용

예측 함

In [22]:
x = np.arange(12).reshape(3, 4)
x.shape

(3, 4)

In [18]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
x.reshape(-1, 1)  # -1은 무시 -> 가변
# 앞에껀 길이가 정해져있지않고, 뒤에꺼 먼저 1로 맞춰서 해라

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [27]:
x.reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])